### ISSUE TITLE
Clarify status of shields branch

### ISSUE THREAD

**Issue by gwarf** [EGI-Foundation/cloud-info-provider#100]
@alvarolopez there is a [shields](https://github.com/EGI-Foundation/cloud-info-provider/tree/shields) branch, I presume it's realted to #97, can we delete it now? 
(you should also have received an invitation to become admin of this repo, can you check?)

**Comment by alvarolopez** [comment]
Yes please :+1:

**Comment by enolfc** [comment]
Branch is gone
