### ISSUE TITLE
"Could not authorize user in project '<os_project_name>'" when getting project's ID through keystoneauth's session

### ISSUE THREAD

**Issue by orviz** [EGI-Foundation/cloud-info-provider#117]
# Short Description of the issue

keystoneauth's session is using the project name in the os_project_id attribute, resulting in a permission denied error (see traceback below).

Moreover the domain has to be added when creating the session as the project is only unique within a given domain in keystone v3. 

## Environment

- Operating System: Debian 9
- python version: 2.7.13
- OpenStack version: affects keystone v3

## Steps to reproduce

Using the following share configuration:
```yaml
shares:
    fedcloud.egi.eu:
            project: VO:fedcloud.egi.eu
            sla: https://egi.eu/sla/fedcloud
            # Type of network: infiniband, gigabiteethernet...
            network_info: UNKNOWN
            membership:
                - VOMS:/fedcloud.egi.eu/Role=VMOperators
```

## Logs, stacktrace, or other symptoms

```shell
Traceback (most recent call last):
  File "/tmp/venv/bin/cloud-info-provider-service", line 10, in <module>
    sys.exit(main())
  File "/tmp/cloud-info-provider-reproduce/cloud_info_provider/core.py", line 244, in main
    print(bdii.render().encode('utf-8'))
  File "/tmp/cloud-info-provider-reproduce/cloud_info_provider/core.py", line 117, in render
    **kwargs)
  File "/tmp/cloud-info-provider-reproduce/cloud_info_provider/core.py", line 56, in _get_info_from_providers
    result = getattr(i, method)(**provider_kwargs)
  File "/tmp/cloud-info-provider-reproduce/cloud_info_provider/providers/openstack.py", line 53, in inner
    self._rescope_project(project)
  File "/tmp/cloud-info-provider-reproduce/cloud_info_provider/providers/openstack.py", line 138, in _rescope_project
    raise exceptions.OpenStackProviderException(msg)
cloud_info_provider.exceptions.OpenStackProviderException: Could not authorize user in project 'VO:fedcloud.egi.eu'
```

# Summary of proposed changes

- Create the keystoneauth's session with project and domain name.
- Add the domain name for a given project in the YAML configuration.

**Comment by gwarf** [comment]
As discussed in the PR, this works if you use (as shown in the sample configuration files) project_id instead fo project names. Project ID's are unique across the domains so there is no need to introduce the domain.
Nevertheless, it may be appropriate to make this more clear, and to had some flexibility and clarity @enolfc proposed the following:
For OpenStack:
```yaml
fedcloud.egi.eu:
  auth:
    project_id: xxxx
  sla: ...
``` 

For OpenNebula:
```yaml
fedcloud.egi.eu:
  auth:
    group: xxxx
  sla: ...
```

Are you OK with this?

**Comment by orviz** [comment]
I have no access to a ONE deployment so I could not test the modifications done in #119 with regards to this framework. We shoulddouble check that everything is right there.
