### ISSUE TITLE
Add GOCDB endpoint id

### ISSUE THREAD

**Issue by enolfc** [EGI-Foundation/cloud-info-provider#120]
# Short Description of the issue

In order to facilitate discovery and linking information the GOCDB id of the service endpoint should be added to the OtherInfo in the Glue Endpoint. 

## Environment

N/A

- Operating System:
- python version:
- OpenStack version:

## Steps to reproduce
N/A

## Logs, stacktrace, or other symptoms
N/A

```shell
output
```

# Summary of proposed changes

Add the GOCDB endpoint id to service endpoint. Probably do some sanity check on URLs too

**Comment by gwarf** [comment]
Fixed by #129
