### ISSUE TITLE
Test if there are non ascii characters in templates

### ISSUE THREAD

**Issue by enolfc** [EGI-Foundation/cloud-info-provider#131]
# Short Description of the issue

We should avoid #126 happening again by automatically testing that there are no non-ascii chars in the templates.

**Comment by gwarf** [comment]
A few possibilities:
* https://unix.stackexchange.com/questions/194435/check-whether-text-contains-non-ascii-characters-in-a-shell-script
* https://bytes.com/topic/python/answers/606938-finding-non-ascii-characters-set-files
* https://nokyotsu.com/qscripts/2010/04/check-if-file-contains-special-non.html
https://stackoverflow.com/questions/35889505/check-that-a-string-contains-only-ascii-characters/35890514

Could be added as a test played by Travis and or/ Jenkins or even tox.
