### ISSUE TITLE
Add creation date to VM images (ApplicationEnvironment)

### ISSUE THREAD

**Issue by enolfc** [EGI-Foundation/cloud-info-provider#14]

**Comment by brucellino** [comment]
can someone describe the issue here in a bit more detail please ? I have no idea what to address or how.

**Comment by enolfc** [comment]
This is probably not relevant anymore as we are moving towards GlueSchema 2.1 makes no sense to go into features here. 

If there is the need for any dates in the new schema I suggest to open an issue for that.
