### ISSUE TITLE
Sometimes the Travis jobs are not reporting errors even if some subtasks are failing

### ISSUE THREAD

**Issue by gwarf** [EGI-Foundation/cloud-info-provider#144]
It was seen a couple of times that travis jobs reported a success even if one of the subtask failed. It's related to task being run into containers and not propagating the error to the parent shell.

**Comment by gwarf** [comment]
Example: https://travis-ci.org/EGI-Foundation/cloud-info-provider/jobs/486491283#L3263-L3268

**Comment by enolfc** [comment]
No longer using travis...
