### ISSUE TITLE
Option --format glue21 doesn't work

### ISSUE THREAD

**Issue by marcoverl** [EGI-Foundation/cloud-info-provider#149]
# Short Description of the issue
The command below fails:
```
$ cloud-info-provider-service --format glue21 --yaml /etc/cloud-info-provider/openstack.yaml --os-tenant-name VO:fedcloud.egi.eu --middleware openstack
```
## Environment

- Operating System: CentOS7
- python version: 2.7.5
- OpenStack version: Rocky

## Steps to reproduce
```
$ cloud-info-provider-service --format glue21 --yaml /etc/cloud-info-provider/openstack.yaml --os-tenant-name VO:fedcloud.egi.eu --middleware openstack
```
using the openstack.yaml as shown in https://pastebin.com/bdtuGaiD 

## Logs, stacktrace, or other symptoms
The command output is:
```
dn: o=glue
objectClass: organization
o: glue

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cloud_info_provider/formatters/base.py", line 41, in _format_template
    return tpl.render(attributes=info)
  File "/usr/lib/python2.7/site-packages/mako/template.py", line 443, in render
    return runtime._render(self, self.callable_, args, data)
  File "/usr/lib/python2.7/site-packages/mako/runtime.py", line 783, in _render
    **_kwargs_for_callable(callable_, data))
  File "/usr/lib/python2.7/site-packages/mako/runtime.py", line 815, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/usr/lib/python2.7/site-packages/mako/runtime.py", line 841, in _exec_template
    callable_(context, *args, **kwargs)
  File "/etc/cloud-info-provider/templates/compute.glue21", line 378, in render_body
    <%
TypeError: string indices must be integers
```
# Summary of proposed changes

things work after commenting with ## the lines from 376 to 395 in
`/etc/cloud-info-provider/templates/compute.glue21`: https://github.com/EGI-Foundation/cloud-info-provider/blob/0.11.2/etc/templates/compute.glue21#L376-L395

**Comment by gwarf** [comment]
Thanks @marcoverl we will look at this ASAP.

**Comment by gwarf** [comment]
So I'm able to reproduce the issue, it seems to happen for the enmr.eu, not with the fedcloud.egi.eu VO.
Will debug this.

**Comment by gwarf** [comment]
OK, so the problem is related to this image that is having traffic rules: https://appdb.egi.eu/store/vappliance/scipioncloud.gpu/vaversion/latest
And in fact the format the template is expecting and the format that is used by the AppDB differ, we will clarify this with @mhaggel.

**Comment by gwarf** [comment]
So for the record, the code is expecting to receive a dict following this syntax:
```
[{
    "protocol": ENUM{all, tcp, udp, icmp, ipsec},
    "type": ENUM{inbound, outbound},
    "range": String,
    "port": String
}]
```
Whereas the image metadata contains this for `ad:traffic_in`:
```
[{:“ad:net_protocol”=>“tcp”, :“ad:net_port”=>“8000:8000", :“ad:net_range”=>“0.0.0.0/0"}]
```

So once discussed with @mhaggel we will fix the code.

**Comment by gwarf** [comment]
OK, escalated to `cloudkeeper` to clarify the format: https://github.com/the-cloudkeeper-project/cloudkeeper/issues/78
