### ISSUE TITLE
Automate release process

### ISSUE THREAD

**Issue by enolfc** [EGI-Foundation/cloud-info-provider#156]
# Short Description of the issue

Current release process requires manually editing several files (rpm and deb specs, zenodo information file, authors, changelog) with same information in slightly different formats. This could be automated with tools like https://github.com/nokia/git-changelog-generator

# Summary of proposed changes

Automate release as much as possible, ideally, creating a release should be just tagging the repo :)

**Comment by gwarf** [comment]
Fully agree, it's really worth having a look as it's currently painful, error-prone and time-consuming.
Some time agoi @brucellino also pointed https://github.com/genuinetools/pepper that could help too.

**Comment by enolfc** [comment]
Now available as github actions
