### ISSUE TITLE
Enforce the usage of a code formatter: black, prettier

### ISSUE THREAD

**Issue by gwarf** [EGI-Foundation/cloud-info-provider#165]
Enforce the usage of a code formatter to have consistent formatting.
For python files [black](https://black.readthedocs.io/en/stable/) can be used.
For other files [prettier](https://prettier.io/) is a nice solution.

Proposed steps:
- [x] setup travis/Jenkins testing for python format conformance using black
- [x] reformat Python files using black
- [ ] setup travis/Jenkins test for other file types we want to format using prettier
- [ ] reformat all supported file type
- [ ] ensure that everything is documented
- [ ] Get a PR merged and break the nice atomic history navigation

**Comment by enolfc** [comment]
This can be closed as we have the superlinter in github
