### ISSUE TITLE
Jenkins jobs are failing

### ISSUE THREAD

**Issue by gwarf** [EGI-Foundation/cloud-info-provider#182]
Jenkins jobs are failing while building the packages as it seems that the appropriate github tag is not checked out so python-build is not able to find the expected source file:
https://jenkins.egi.ifca.es/blue/organizations/jenkins/Pipeline-as-Code%2Fcloud-info-provider/detail/master/57/pipeline/

![Screenshot 2019-11-06 at 17 53 31](https://user-images.githubusercontent.com/451417/68319307-69fa0280-00be-11ea-83d0-a121af2e2086.png)

**Comment by gwarf** [comment]
Hi @orviz would you be able to provide some help with this?

**Comment by orviz** [comment]
sure @gwarf I'll take a look

**Comment by orviz** [comment]
The RPM building stage failed as a consequence of the missing `python-pbr` module. EPEL repository was not available in the environment so this requirement was not installed. It has been [fixed](https://github.com/indigo-dc/ci-images/commit/dfedd5de81f00360246014967d5f779b6366c567) in the relevant Docker image used for running this stage.

The PR above complements this fix.

**Comment by gwarf** [comment]
Thanks @orviz !
