### ISSUE TITLE
Use "stevedore" to load classes

### ISSUE THREAD

**Issue by alvarolopez** [EGI-Foundation/cloud-info-provider#25]
We are using a simple classloader for loading the providers, we should rather move to stevedore and define entrypoints for the classes, instead of referencing them by the full namespace.

**Comment by brucellino** [comment]
@alvarolopez can you provide some suggestion of how you would do this with stevedore, compared to how things are done now ? 

For example where would we use stevedore (which files ? all in `cloud_info` ?)

**Comment by alvarolopez** [comment]
We are using an `importutils` module that loads the classes for the providers [here (cloud_info/core.py#L29)](
https://github.com/EGI-Foundation/cloud-info-provider/blob/171843a75ddf0c49d5fa178f0d1d613b183df51a/cloud_info/core.py#L29).

Although this works, it is quite limited, and we should move to either plugins or extensions using stevedore (depending on which loading pattern we do want to use). The main advantage is that, since stevedore relies on entrypoints, we can load any class (even external to the project) without modifying our code. With the current implementation, the mapping is hardcoded.

I can work on this, but I cannot provide an ETA though (although I would say that this is too low priority).

**Comment by enolfc** [comment]
I suggest to move this to a 1.x update as it will require some refactoring

**Comment by alvarolopez** [comment]
This is being carried out here (WIP) https://github.com/indigo-dc/cloud-info-provider-deep/pull/10

**Comment by alvarolopez** [comment]
Probably during January. The code is ready to be used, the only missing piece are the unit tests.

**Comment by gwarf** [comment]
Fixed by #137
