### ISSUE TITLE
Publish info on non-public flavors

### ISSUE THREAD

**Issue by enolfc** [EGI-Foundation/cloud-info-provider#82]
# Short Description of the issue

Flavours in OpenStack can be set as non-public, meaning they are only available for a given project. Although this is not the default behaviour, it may be a valid setup for the support of a VO on a site. Current code skips these: 

https://github.com/EGI-Foundation/cloud-info-provider/blob/171843a75ddf0c49d5fa178f0d1d613b183df51a/cloud_info/providers/openstack.py#L272

It should be allowed to publish them (maybe enable via configuration)

**Comment by gwarf** [comment]
Thanks @enolfc.
@alvarolopez do you have any remarks regarding this? What was the reasoning behind adding such a check to filter out non-public images?

**Comment by gwarf** [comment]
From https://docs.openstack.org/nova/pike/admin/flavors.html 

**isPublic**: `Boolean value, whether flavor is available to all users or private to the project it was created in. Defaults to True.`
