### ISSUE TITLE
Enable complete testing inside Jenkins

### ISSUE THREAD

**Issue by gwarf** [EGI-Foundation/cloud-info-provider#84]
IFCA is operating a Jenkins deployment that can be used by EGI and used to test the cloud-info-provider.

Tests that should be enabled and used to validate PR:
- [ ] Code Style
- [ ] Unit test
- [ ] Code coverage

Future test to be added:
- [ ] Integration tests

**Comment by brucellino** [comment]
@gwarf  code style is probably easy (flake8, yamllint) - but have you got ideas about how to do the integration test?

**Comment by gwarf** [comment]
For code style there is already some work integrated using `tox` so the main task will be to validate that all jobs are running.

Integration testing will be a big subject, no clear idea yet, don't hesitate to provide some.
For new release could automatically deploy a real test environment to do some real testing. But we may also want to have something that could be run more quickly using some static/mock stuff.

**Comment by brucellino** [comment]
Looks like this is done in #96
