### ISSUE TITLE
Use a messaging queue to transport cloud-info-provider output

### ISSUE THREAD

**Issue by gwarf** [EGI-Foundation/cloud-info-provider#85]
We should use a messaging queue to transport cloud-info-provider output.
Either a component should be added to this project or a dedicated project should be created.

**Comment by alvarolopez** [comment]
I would go with a different publisher, probably as a plugin to be loaded whenever #25 is done...

**Comment by enolfc** [comment]
For the time being, this will be handled by a wrapper and gradually moved to the cloud-info-provider.

**Comment by kkoumantaros** [comment]
Is there a pattern you've agreed upon for the topic naming  is it something like fedcloud_site_name or something similar ?

**Comment by enolfc** [comment]
The agreed naming so far is:

  SITE_<name of site in GOCDB>_ENDPOINT_<identifier of the endpoint in GOCDB>

Adding @mhaggel to ensure this is still ok

**Comment by mhaggel** [comment]
Yes i confirm that this is ok.

Another way to go, less friendly though, could be:
SITE_<identifier of the site in GOCDB>_ENDPOINT_<identifier of the endpoint in GOCDB>

**Comment by kkoumantaros** [comment]
Ok we can close this issue with the decision that for topics we will use SITE_<name of site in GOCDB>_ENDPOINT_<identifier of the endpoint in GOCDB>

**Comment by mhaggel** [comment]
Just nu i realized that the github editor does render my previous comment correctly.
I wrote:
Another way to go, less friendly though, could be:
SITE_ < identifier of the site in GOCDB > \_ENDPOINT_ < identifier of the endpoint in GOCDB >

NOT just SITE_ENDPOINT

**Comment by enolfc** [comment]
This is partially fixed in #178 . Only missing bit would be to automatically generate the topic for publication, which can be done easily with code already available but it would require some refactoring to get the information to the right place.

**Comment by enolfc** [comment]
This is done now as of #178, improvements may come later
